name: "Automatic pre-release"

on:
  push:
    tags:
      - "v*-*"

jobs:
  auto_pre_release:
    name: Automatic pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tools/generate-release-assets.sh
        id: generate_release_assets
        run: |
          ASSETS=$(tools/generate-release-assets.sh)
          echo assets="$ASSETS" >> $GITHUB_OUTPUT

      - name: Automatic pre-release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          files: ${{ steps.generate_release_assets.outputs.assets }}
